spring:
  datasource:
    url: "jdbc:h2:./library;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE"
    username: user
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true