version: '3.7'

services:
  library-backend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_PROFILE: no-frontend
    image: 'evawe/library-backend:1'
    container_name: library-backend
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      - db
    environment:
      - MONGODB_DATABASE=library
      - MONGODB_PORT=27017
      - MONGODB_HOST=db
      - JASYPT_PASSWORD=${JASYPT_MASTER_PASSWORD}
    restart: always


  db:
    env_file: .env
    image: 'mongo:latest'
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # можно sed'ом в CI заменить, что бы не палить здесь
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CONTAINER_PASSWORD} # можно sed'ом в CI заменить, что бы не палить здесь
    ports:
      - "27017:27017"
    networks:
      - library-network

networks:
  library-network:
    name: library-network
