spring:
  data:
    mongodb:
        authentication-database: admin
        database: library
        port: 27017
        host: localhost



mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.dankoy.hw8.core.mongock.changelogs