management:
  endpoints:
    web:
      exposure:
        include: info, health, beans


hw3:
  locale: en_US
  answerTemplate: "\ \ %d) %s"
  questionTemplate: "%d) %s"
  amountOfCorrectAnswersToPassTest: 3



